import json
import os
import re
from datetime import datetime, timezone
from xml.etree import ElementTree

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials


# ============================================================
# CONFIGURATION
# ============================================================

INPUT_FILE = "youtube_top_50.json"
OUTPUT_FILE = "youtube_transcripts.json"
CLIENT_SECRET_FILE = "client_secret.json"

# YouTube OAuth scope required for caption operations
SCOPES = [
    "https://www.googleapis.com/auth/youtube.force-ssl"
]

# Only process the top N videos from each category
TOP_N_PER_CATEGORY = 10


# ============================================================
# YOUTUBE AUTHENTICATION
# ============================================================

def get_youtube_client():
    """
    Authenticate with YouTube using OAuth.

    The first time this is run, a browser window will open so
    you can authorize the application.
    """

    credentials = None

    # Reuse existing credentials
    if os.path.exists("token.json"):
        credentials = Credentials.from_authorized_user_file(
            "token.json",
            SCOPES
        )

    # Refresh expired credentials
    if credentials and credentials.expired and credentials.refresh_token:
        credentials.refresh(Request())

    # First-time authentication
    if not credentials or not credentials.valid:

        if not os.path.exists(CLIENT_SECRET_FILE):
            raise FileNotFoundError(
                f"Could not find {CLIENT_SECRET_FILE}"
            )

        flow = InstalledAppFlow.from_client_secrets_file(
            CLIENT_SECRET_FILE,
            SCOPES
        )

        credentials = flow.run_local_server(
            port=0
        )

        # Save credentials for future runs
        with open("token.json", "w") as token:
            token.write(credentials.to_json())

    return build(
        "youtube",
        "v3",
        credentials=credentials
    )


# ============================================================
# LOAD PREVIOUS TRANSCRIPTS
# ============================================================

def load_existing_transcripts():
    """
    Load transcripts that have already been collected.

    This prevents us from downloading the same transcript
    repeatedly on subsequent daily runs.
    """

    if not os.path.exists(OUTPUT_FILE):
        return {
            "transcripts": {}
        }

    try:

        with open(
            OUTPUT_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            return json.load(file)

    except (json.JSONDecodeError, OSError):

        return {
            "transcripts": {}
        }


# ============================================================
# LOAD DAILY VIDEO DATA
# ============================================================

def load_videos():
    """
    Read the JSON file generated by the previous script.
    """

    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(
            f"Could not find {INPUT_FILE}"
        )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    return data


# ============================================================
# GET TOP 10 FROM EACH CATEGORY
# ============================================================

def get_top_videos(data):
    """
    Get the top 10 videos from each category.

    The input file may contain 50 videos, but only the
    first TOP_N_PER_CATEGORY are processed.
    """

    videos_by_category = {}

    for video in data.get("videos", []):

        category = video.get("category")

        if category not in videos_by_category:
            videos_by_category[category] = []

        if len(videos_by_category[category]) < TOP_N_PER_CATEGORY:
            videos_by_category[category].append(video)

    videos = []

    for category_videos in videos_by_category.values():
        videos.extend(category_videos)

    return videos


# ============================================================
# GET CAPTION TRACKS
# ============================================================

def get_caption_tracks(youtube, video_id):
    """
    Get caption tracks available for a video.

    Returns an empty list if captions aren't available.
    """

    try:

        response = youtube.captions().list(
            part="snippet",
            videoId=video_id
        ).execute()

        return response.get("items", [])

    except HttpError as error:

        print(
            f"    Could not retrieve captions: {error}"
        )

        return []


# ============================================================
# CHOOSE CAPTION TRACK
# ============================================================

def choose_caption_track(captions):
    """
    Prefer English captions.

    Priority:
    1. English manual captions
    2. English automatic captions
    3. Any available caption track
    """

    if not captions:
        return None

    # Prefer English
    english = [
        caption
        for caption in captions
        if caption.get("snippet", {}).get("language") == "en"
    ]

    if english:

        # Prefer manually created captions
        manual = [
            caption
            for caption in english
            if caption.get("snippet", {}).get("trackKind") != "ASR"
        ]

        if manual:
            return manual[0]

        return english[0]

    # Fall back to any caption
    return captions[0]


# ============================================================
# DOWNLOAD CAPTION
# ============================================================

def download_caption(youtube, caption_id):
    """
    Download a caption track as SRT.

    Note:
    The exact download format returned by YouTube can vary,
    so we parse both XML-style and SRT-style responses.
    """

    try:

        response = youtube.captions().download(
            id=caption_id,
            tfmt="srt"
        ).execute()

        if isinstance(response, bytes):
            return response.decode(
                "utf-8",
                errors="replace"
            )

        return response

    except HttpError as error:

        print(
            f"    Could not download caption: {error}"
        )

        return None


# ============================================================
# CLEAN SRT TRANSCRIPT
# ============================================================

def clean_srt(srt_text):
    """
    Convert SRT caption text into normal readable text.
    """

    if not srt_text:
        return ""

    lines = srt_text.splitlines()

    cleaned = []

    for line in lines:

        line = line.strip()

        # Skip blank lines
        if not line:
            continue

        # Skip subtitle numbers
        if line.isdigit():
            continue

        # Skip timestamps
        if "-->" in line:
            continue

        # Remove basic HTML tags
        line = re.sub(
            r"<[^>]+>",
            "",
            line
        )

        cleaned.append(line)

    # Remove duplicate consecutive captions
    final_lines = []

    for line in cleaned:

        if not final_lines or line != final_lines[-1]:
            final_lines.append(line)

    return " ".join(final_lines)


# ============================================================
# GET TRANSCRIPT
# ============================================================

def get_transcript(youtube, video_id):
    """
    Find and download the best available transcript.
    """

    captions = get_caption_tracks(
        youtube,
        video_id
    )

    if not captions:
        return None, None

    caption = choose_caption_track(
        captions
    )

    if not caption:
        return None, None

    caption_id = caption["id"]

    snippet = caption.get(
        "snippet",
        {}
    )

    language = snippet.get(
        "language",
        "unknown"
    )

    srt = download_caption(
        youtube,
        caption_id
    )

    if not srt:
        return None, None

    transcript = clean_srt(
        srt
    )

    return transcript, language


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 60)
    print("        YouTube Daily Transcript Collector")
    print("=" * 60)
    print()

    # --------------------------------------------------------
    # LOAD DAILY DATA
    # --------------------------------------------------------

    try:

        daily_data = load_videos()

    except Exception as error:

        print(f"Error loading daily data: {error}")
        return

    # --------------------------------------------------------
    # GET TOP 10 PER CATEGORY
    # --------------------------------------------------------

    videos = get_top_videos(
        daily_data
    )

    print(
        f"Found {len(videos)} videos to process."
    )

    print()

    # --------------------------------------------------------
    # LOAD EXISTING TRANSCRIPTS
    # --------------------------------------------------------

    transcript_data = load_existing_transcripts()

    if "transcripts" not in transcript_data:
        transcript_data["transcripts"] = {}

    existing = transcript_data["transcripts"]

    # --------------------------------------------------------
    # YOUTUBE AUTHENTICATION
    # --------------------------------------------------------

    try:

        youtube = get_youtube_client()

    except Exception as error:

        print(
            f"Authentication error: {error}"
        )

        return

    # --------------------------------------------------------
    # PROCESS VIDEOS
    # --------------------------------------------------------

    new_transcripts = 0
    skipped = 0
    unavailable = 0

    for index, video in enumerate(videos, start=1):

        video_id = video["video_id"]
        title = video.get(
            "title",
            "Unknown title"
        )

        category = video.get(
            "category",
            "Unknown"
        )

        print(
            f"[{index}/{len(videos)}] "
            f"{category}: {title}"
        )

        # ----------------------------------------------------
        # SKIP IF ALREADY COLLECTED
        # ----------------------------------------------------

        if video_id in existing:

            print("    Already collected — skipping.")
            skipped += 1
            print()

            continue

        # ----------------------------------------------------
        # GET TRANSCRIPT
        # ----------------------------------------------------

        transcript, language = get_transcript(
            youtube,
            video_id
        )

        # ----------------------------------------------------
        # SAVE RESULT
        # ----------------------------------------------------

        collected_at = datetime.now(
            timezone.utc
        ).isoformat()

        if transcript:

            existing[video_id] = {

                "video_id": video_id,

                "title": title,

                "channel": video.get(
                    "channel"
                ),

                "category": category,

                "video_url": video.get(
                    "url"
                ),

                "published_at": video.get(
                    "published_at"
                ),

                "views_when_collected": video.get(
                    "views"
                ),

                "likes_when_collected": video.get(
                    "likes"
                ),

                "comments_when_collected": video.get(
                    "comments"
                ),

                "transcript_language": language,

                "collected_at": collected_at,

                "transcript": transcript
            }

            new_transcripts += 1

            print(
                f"    Transcript collected "
                f"({language})"
            )

        else:

            existing[video_id] = {

                "video_id": video_id,

                "title": title,

                "category": category,

                "video_url": video.get(
                    "url"
                ),

                "collected_at": collected_at,

                "status": "unavailable",

                "transcript": None
            }

            unavailable += 1

            print(
                "    Transcript unavailable."
            )

        print()

    # --------------------------------------------------------
    # UPDATE FILE METADATA
    # --------------------------------------------------------

    transcript_data["last_run"] = datetime.now(
        timezone.utc
    ).isoformat()

    transcript_data["videos_checked_this_run"] = len(
        videos
    )

    transcript_data["new_transcripts_this_run"] = (
        new_transcripts
    )

    transcript_data["already_collected"] = skipped

    transcript_data["unavailable"] = unavailable

    # --------------------------------------------------------
    # SAVE
    # --------------------------------------------------------

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            transcript_data,
            file,
            indent=4,
            ensure_ascii=False
        )

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print("=" * 60)
    print("Complete!")
    print()
    print(f"Videos checked:       {len(videos)}")
    print(f"New transcripts:      {new_transcripts}")
    print(f"Already collected:    {skipped}")
    print(f"Unavailable:          {unavailable}")
    print()
    print(f"Saved to: {OUTPUT_FILE}")
    print("=" * 60)


if __name__ == "__main__":
    main()

